// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatBuffers
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct TestStruct1 : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static TestStruct1 GetRootAsTestStruct1(ByteBuffer _bb) { return GetRootAsTestStruct1(_bb, new TestStruct1()); }
  public static TestStruct1 GetRootAsTestStruct1(ByteBuffer _bb, TestStruct1 obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public TestStruct1 __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public FlatBuffers.Vec3? Position { get { int o = __p.__offset(4); return o != 0 ? (FlatBuffers.Vec3?)(new FlatBuffers.Vec3()).__assign(o + __p.bb_pos, __p.bb) : null; } }

  public static void StartTestStruct1(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddPosition(FlatBufferBuilder builder, Offset<FlatBuffers.Vec3> positionOffset) { builder.AddStruct(0, positionOffset.Value, 0); }
  public static Offset<FlatBuffers.TestStruct1> EndTestStruct1(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatBuffers.TestStruct1>(o);
  }
  public TestStruct1T UnPack() {
    var _o = new TestStruct1T();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(TestStruct1T _o) {
    _o.Position = this.Position.HasValue ? this.Position.Value.UnPack() : null;
  }
  public static Offset<FlatBuffers.TestStruct1> Pack(FlatBufferBuilder builder, TestStruct1T _o) {
    if (_o == null) return default(Offset<FlatBuffers.TestStruct1>);
    StartTestStruct1(builder);
    AddPosition(builder, FlatBuffers.Vec3.Pack(builder, _o.Position));
    return EndTestStruct1(builder);
  }
}

public class TestStruct1T
{
  public FlatBuffers.Vec3T Position { get; set; }

  public TestStruct1T() {
    this.Position = new FlatBuffers.Vec3T();
  }
}


}
