// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatBuffers
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct TestByte : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static TestByte GetRootAsTestByte(ByteBuffer _bb) { return GetRootAsTestByte(_bb, new TestByte()); }
  public static TestByte GetRootAsTestByte(ByteBuffer _bb, TestByte obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public TestByte __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public sbyte Scalar { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetSbyte(o + __p.bb_pos) : (sbyte)0; } }
  public bool MutateScalar(sbyte scalar) { int o = __p.__offset(4); if (o != 0) { __p.bb.PutSbyte(o + __p.bb_pos, scalar); return true; } else { return false; } }

  public static Offset<FlatBuffers.TestByte> CreateTestByte(FlatBufferBuilder builder,
      sbyte scalar = 0) {
    builder.StartTable(1);
    TestByte.AddScalar(builder, scalar);
    return TestByte.EndTestByte(builder);
  }

  public static void StartTestByte(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddScalar(FlatBufferBuilder builder, sbyte scalar) { builder.AddSbyte(0, scalar, 0); }
  public static Offset<FlatBuffers.TestByte> EndTestByte(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatBuffers.TestByte>(o);
  }
  public TestByteT UnPack() {
    var _o = new TestByteT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(TestByteT _o) {
    _o.Scalar = this.Scalar;
  }
  public static Offset<FlatBuffers.TestByte> Pack(FlatBufferBuilder builder, TestByteT _o) {
    if (_o == null) return default(Offset<FlatBuffers.TestByte>);
    return CreateTestByte(
      builder,
      _o.Scalar);
  }
}

public class TestByteT
{
  public sbyte Scalar { get; set; }

  public TestByteT() {
    this.Scalar = 0;
  }
}


}
