// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatBuffers
{

public enum TestEnum : sbyte
{
  None = 0,
  One = 1,
  Two = 2,
};


}
